---

computername: Kerngehäuse
hostname: kerngehaeuse

system_save_application_state_on_quit: yes
system_expand_save_panel_by_default: yes
system_expand_print_panel_by_default: yes
system_show_file_extensions_warning: no
system_warn_before_emptying_the_trash: yes
system_use_f_keys_as_standard_function_keys: no
system_index_network_storage_with_spotlight: no
trackpad_tap_to_click: yes

screensaver_ask_for_password: no
screensaver_ask_for_password_in_seconds: 5

shell_path: /usr/local/bin/zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - homebrew/cask-versions

homebrew_apps:
  - 1password
  - fliqlo
  - font-fira-code
  - font-roboto
  - gpg-suite
  - iina
  - iterm2
  - kaleidoscope
  - osxfuse
  - intellij
  - plug
  - sequel-pro
  - slack
  - textual
  - keka
  - tower
  - transmit

homebrew_packages:
  - bash
  - composer
  - curl
  - git
  - hub
  - httpie
  - jq
  - libmemcached
  - macvim
  - memcached
  - mysql@5.7
  - node
  - php@7.2
  - pkg-config
  - python
  - ruby
  - wget
  - yadm
  - zlib
  - zsh

mas_apps:
  - { name: 1Blocker, id: 1107421413 }
  - { name: Carbonize, id: 1451177988 }
  - { name: Pages, id: 409201541 }
  - { name: Numbers, id: 409203825 }
  - { name: Keynote, id: 409183694 }
  - { name: Garageband, id: 682658836 }
  - { name: iMovie, id: 408981434 }
  - { name: Pixelmator, id: 407963104 }
  - { name: iAWriter, id: 775737590 }
  - { name: Integrity, id: 513610341 }
  - { name: DaVinciResolve, id: 571213070 }
  - { name: iAWriter, id: 775737590 }
  - { name: xCode, id: 497799835 }
  - { name: Telefon, id: 406825478 }


composer_packages:
  - name: hirak/prestissimo
  - name: hirak/prestissimo

npm_packages:
  - name: webpack
  - name: json2csv
